<?php
/**
 * Yet another simple CMS
 *
 * @copyright 2014 Jakub Kaderka
 * @license GNU General Public License, version 2; see LICENSE.txt
 */

//no direct access
defined("IN_CMS") or die("Unauthorized access");
?>

<h1><?= $files_edit ?></h1>
<div id="edit_files">
	<form action="" method="post" enctype="multipart/form-data">
		<b><?= $upload ?>:</b>
		<input type="file" name="upload[]" multiple="multiple"/>
		<input type="hidden" name="upload" value="1"/>
		<select name="dir">
			<?php foreach ($dirs as $d) : ?>
			<option value="<?= $d ?>" <?php if ($dir_selected == $d): ?>selected="selected"<?php endif ?>><?= $d ?></option>
			<?php endforeach ?>
		</select>
		<input type="submit" value="<?= $send ?>"/>
	</form>

	<form action="" method="post">
		<b><?= $new_dir ?>:</b>
		<input type="text" name="dir"/>
		<input type="hidden" name="new_dir" value="1"/>
		<input type="submit" value="<?= $send ?>"/>
	</form>

	<?php if ($files || $dirs) : ?>
	<br/>
	<form action="" method="post"><table>
		<tr>
			<td><?= $name ?></td>
			<td><?= $delete ?></td>
		</tr>
		<?php foreach ($dirs as $d) : if ($d != "./") :?>
		<tr>
			<td><?= $d ?></td>
			<td><input type="checkbox" name="files[<?= $d ?>]"/></td>
		</tr>
		<?php endif; endforeach ?>
		<?php foreach ($files as $f) :?>
		<tr>
			<td><?= $f ?></td>
			<td><input type="checkbox" name="files[<?= $f ?>]"/></td>
		</tr>
		<?php endforeach ?>
		<tr><td>
			<input type="hidden" name="delete" value="1"/>
			<input type="submit" value="<?= $send ?>"/>
		</td></tr>
	</form></table>
	<?php endif ?>
</div>
