<?php
/**
 * Yet another simple CMS
 *
 * @copyright 2014 Jakub Kaderka
 * @license GNU General Public License, version 2; see LICENSE.txt
 */

//no direct access
defined("IN_CMS") or die("Unauthorized access");
?>

<div id="admin_menu">
	<a href="<?= $logout_link ?>"><?= $logout ?></a><br/>
	<hr/>
	<b><?= $edit ?>:</b>
	<?php foreach($actions as $a => $l) : ?>
	<a class="admin_menu_item" href="<?= $l ?>"><?= $a ?></a>
	<?php endforeach ?>

</div>
<hr/>

<?php if ($this->controller) echo $this->controller->printView(); ?>
