<?php
/**
 * Yet another simple CMS
 *
 * @copyright 2014 Jakub Kaderka
 * @license GNU General Public License, version 2; see LICENSE.txt
 */

//no direct access
defined("IN_CMS") or die("Unauthorized access");
?>

<div id="cathegory">
<?php foreach ($articles as $a) : ?>
	<div class="cat_item">
		<h2 class="cat_item_title">
			<a href="<?= $a['link'] ?>"><?= $a['title'] ?></a>
		</h2>
		<p class="cat_item_desc"><?= $a['description'] ?></p>
		<div class="cat_item_info"><?= $a['date'] ?></div>
	</div>
<?php endforeach ?>

<?php
	/* Not the best solution, but it's the simplest one */
	require "views/paging.phtml";
?>
</div>
