<?php
/**
 * Yet another simple CMS
 *
 * @copyright 2014 Jakub Kaderka
 * @license GNU General Public License, version 2; see LICENSE.txt
 */

//no direct access
defined("IN_CMS") or die("Unauthorized access");
?>

<?php if ($allowed) : ?>
<div id="comments">
	<div id="com_all">
	<?php foreach ($comments as $comment) : ?>
		<div class="comment">
			<div class="com_head">
				<b><?= e($comment['nickname']) ?></b><br/>
				<div class="com_date"><?= $comment['date'] ?></div>
			</div>
			<div class="com_text">
				<?= e($comment['text']) ?>
			</div>
		</div>
	<?php endforeach ?>
	</div>
	<?php if ($allowed > 0) : ?>
	<a href="<?= $link_add ?>"><?= $add_comment ?></a>
	<?php else : ?>
	<b><?= $not_allowed ?></b>
	<?php endif ?>
</div>
<?php endif ?>
