<?php
/**
 * Yet another simple CMS
 *
 * @copyright 2014 Jakub Kaderka
 * @license GNU General Public License, version 2; see LICENSE.txt
 */

//no direct access
defined("IN_CMS") or die("Unauthorized access");
?>

<h1><?= $article_name?></h1>
<form id="com_form" method="post" action="<?= $action ?>">
<div>
	<b><?= $nickname ?></b><br/>
	<input type="text" name="nick" value="<?= $nick ?>"/><br/>

	<b><?= $comment ?></b><br/>
	<textarea name="text" cols="70" rows="15"><?= $text ?></textarea><br/>

	<b><?= $antispam ?></b><input type="text" name="aq" size="16"/><br/>
	<input type="submit" value="<?= $send ?>"/>
</div>
</form>
