<?php
/**
 * Yet another simple CMS
 *
 * @copyright 2014 Jakub Kaderka
 * @license GNU General Public License, version 2; see LICENSE.txt
 */

//no direct access
defined("IN_CMS") or die("Unauthorized access");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $lang ?>" lang="<?= $lang ?>">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-language" content="<?= $lang ?>" />

	<title><?= $title ?></title>

	<link rel="stylesheet" type="text/css" href="<?= $base ?>files/page/main.css" />
	<link rel="stylesheet" type="text/css" href="<?= $base ?>files/page/theme.css" />
	<link rel="shortcut icon" type="image/x-icon" href="<?= $base ?>files/page/favicon.ico"/>
</head>
<body>
<div id="wrapper">
	<div id="msg_box">
		<?= $message ?>
	</div>
</div>
</body>
</html>
