<?php
/**
 * Yet another simple CMS
 *
 * @copyright 2014 Jakub Kaderka
 * @license GNU General Public License, version 2; see LICENSE.txt
 */

//no direct access
defined("IN_CMS") or die("Unauthorized access");
?>

<div id="page">
	<h1 id="page_title"><?= $title ?></h1>
	<div id="page_content">
		<?= $content ?>
	</div>
	<div id="page_date"> <?= $date ?> </div>
</div>
<?php $this->comments->printView() ?>

